use crate::{
    ast,
    filesystem::{generate_text_file, GeneratedFile},
    typecheck,
};
use std::{
    collections::{BTreeMap, HashMap},
    path::Path,
};

/// Pure descriptors share the compiled query IDs and codecs, never SQL or browser code.
pub fn generate(
    context: &typecheck::Context,
    info: &HashMap<String, typecheck::QueryInfo>,
    queries: &ast::QueryList,
    core: &Path,
    files: &mut Vec<GeneratedFile<String>>,
) {
    let version = crate::generate::manifest::fingerprint(context, queries, info);
    let mut groups: BTreeMap<String, Vec<&ast::Query>> = BTreeMap::new();
    for def in &queries.queries {
        if let ast::QueryDef::Query(q) = def {
            if q.operation != ast::QueryOperation::Query {
                if let Some(i) = info.get(&q.name) {
                    groups.entry(i.primary_db.clone()).or_default().push(q);
                }
            }
        }
    }
    let mut index = String::new();
    for (ns, operations) in &groups {
        let name = if ns == "_default" { "Main" } else { ns };
        let mut text = String::from("// Generated by Pyre. Pure compiled-operation descriptors.\nimport { namespace, scopedEdit, scopedBatch, type EditOperation, type Edit, type Created, type Updated, type Deleted, type JsonInput } from '@pyre/core/local-edits';\n");
        text.push_str(&format!("declare const namespaceBrand: unique symbol;\nexport type {name} = typeof namespaceBrand;\nexport const {name} = namespace<{name}>({}, {});\nexport const batch = scopedBatch({name});\n", json(ns), json(&version)));
        let mut records: BTreeMap<String, Vec<String>> = BTreeMap::new();
        let mut commands = Vec::new();
        let mut ids = BTreeMap::new();
        for table in context.tables.values() {
            for col in ast::collect_columns(&table.record.fields) {
                match &col.type_ {
                    ast::ColumnType::Int if ast::is_primary_key(&col) => {
                        ids.insert(table.record.name.clone(), "number");
                    }
                    ast::ColumnType::IdInt { table: brand } => {
                        ids.insert(
                            if brand.is_empty() {
                                table.record.name.clone()
                            } else {
                                brand.clone()
                            },
                            "number",
                        );
                    }
                    ast::ColumnType::IdUuid { table: brand } => {
                        ids.insert(
                            if brand.is_empty() {
                                table.record.name.clone()
                            } else {
                                brand.clone()
                            },
                            "string",
                        );
                    }
                    _ => {}
                }
            }
        }
        for (brand, primitive) in ids {
            if !brand.is_empty() {
                text.push_str(&format!(
                    "export type {brand}Id = {primitive} & {{ readonly __brand: '{brand}' }};\n"
                ));
            }
        }
        let mut operation_bindings = Vec::new();
        for (operation_index, q) in operations.iter().enumerate() {
            let module = crate::ext::string::decapitalize(&q.name);
            let metadata = format!("$metadata{operation_index}");
            let input = format!("$input{operation_index}");
            let operation = format!("$operation{operation_index}");
            operation_bindings.push(operation.clone());
            text.push_str(&format!(
                "import * as {metadata} from '../core/queries/metadata/{module}';\n"
            ));
            let table = q.fields.iter().find_map(|f| match f {
                ast::TopLevelQueryField::Field(f) => context.tables.get(&f.name),
                _ => None,
            });
            let generated =
                table.and_then(|t| crate::generated_queries::generated_edit(q, t).map(|g| (t, g)));
            text.push_str(&format!("type {input} = {{\n"));
            for arg in &q.args {
                let reference = if q.generated_crud {
                    table
                        .and_then(|t| {
                            ast::collect_columns(&t.record.fields)
                                .into_iter()
                                .find(|c| c.name == arg.name)
                        })
                        .and_then(|c| {
                            if matches!(c.type_, ast::ColumnType::ForeignKey { .. }) {
                                Some(c.type_.to_string())
                            } else {
                                None
                            }
                        })
                } else {
                    None
                };
                let branded = reference.as_deref().or(arg.type_.as_deref()).and_then(|s| {
                    let ast::ColumnType::ForeignKey {
                        schema,
                        table: target,
                        field,
                        ..
                    } = ast::ColumnType::from_str(s)
                    else {
                        return None;
                    };
                    context
                        .tables
                        .values()
                        .find(|t| {
                            t.record.name.eq_ignore_ascii_case(&target)
                                && schema.as_ref().is_none_or(|s| &t.schema == s)
                        })
                        .and_then(|t| {
                            ast::collect_columns(&t.record.fields)
                                .into_iter()
                                .find(|c| c.name == field)
                                .map(|c| (t, c))
                        })
                        .and_then(|(t, c)| match &c.type_ {
                            ast::ColumnType::Int if ast::is_primary_key(&c) => Some(format!(
                                "{}Id{}",
                                t.record.name,
                                if arg.nullable { " | null" } else { "" }
                            )),
                            ast::ColumnType::IdInt { table }
                            | ast::ColumnType::IdUuid { table } => Some(format!(
                                "{}Id{}",
                                if table.is_empty() {
                                    &t.record.name
                                } else {
                                    table
                                },
                                if arg.nullable { " | null" } else { "" }
                            )),
                            _ => None,
                        })
                });
                let ty = branded
                    .unwrap_or_else(|| format!("JsonInput<{metadata}.Input[{}]>", json(&arg.name)));
                // Client UUID creation accepts a fresh UUID; references and existing targets remain branded.
                let ty = if generated.as_ref().is_some_and(|(_, (kind, pk, _))| {
                    *kind == "create"
                        && pk.name == arg.name
                        && matches!(pk.type_, ast::ColumnType::IdUuid { .. })
                }) {
                    "string".into()
                } else {
                    ty
                };
                text.push_str(&format!(
                    "  readonly {}{}: {};\n",
                    json(&arg.name),
                    if arg.omittable { "?" } else { "" },
                    ty
                ));
            }
            text.push_str("};\n");
            let result = if let Some((owner, (kind, pk, _))) = &generated {
                let id = match &pk.type_ {
                    ast::ColumnType::Int => format!("{}Id", owner.record.name),
                    ast::ColumnType::IdInt { table } | ast::ColumnType::IdUuid { table } => {
                        format!(
                            "{}Id",
                            if table.is_empty() {
                                &owner.record.name
                            } else {
                                table
                            }
                        )
                    }
                    _ => panic!("unsupported edit identity"),
                };
                format!(
                    "{}<{id}>",
                    match *kind {
                        "create" => "Created",
                        "update" => "Updated",
                        _ => "Deleted",
                    }
                )
            } else {
                format!("{metadata}.Result")
            };
            text.push_str(&format!("const {operation}: EditOperation<{input}, {result}> = Object.freeze({{\n  id: {metadata}.meta.id,\n  parseInput(value: unknown): {input} {{\n    {metadata}.RawInputValidator.strict().parse(value);\n    {metadata}.meta.InputValidator.strict().parse(value);\n"));
            if let Some((_, (kind, _, writable))) = &generated {
                if *kind == "update" {
                    text.push_str(&format!("    if (!{}.some(key => Object.prototype.hasOwnProperty.call(value, key))) throw new Error('InvalidEdit');\n", serde_json::to_string(writable).unwrap()));
                }
            }
            text.push_str(&format!("    return value as {input};\n  }},\n"));
            if let Some((table, (kind, pk, writable))) = &generated {
                let check = if matches!(pk.type_, ast::ColumnType::IdUuid { .. }) {
                    "typeof id === 'string' && id.length === 36 && /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id)"
                } else {
                    "typeof id === 'number' && Number.isSafeInteger(id)"
                };
                text.push_str(&format!("  decodeResult(value: unknown): {result} {{ const id = (value as any)?.id; if (!({check})) throw new Error('InvalidResult'); return {{ id }} as {result}; }},\n"));
                let columns = ast::collect_columns(&table.record.fields);
                let safe = table.record.fields.iter().any(|f| {
                    matches!(
                        f,
                        ast::Field::FieldDirective(ast::FieldDirective::Permissions(
                            ast::PermissionDetails::Public
                        ))
                    )
                }) && (*kind == "delete"
                    || columns.iter().all(|c| {
                        matches!(
                            c.type_,
                            ast::ColumnType::String
                                | ast::ColumnType::Int
                                | ast::ColumnType::Float
                                | ast::ColumnType::Bool
                                | ast::ColumnType::IdInt { .. }
                                | ast::ColumnType::IdUuid { .. }
                        )
                    }));
                let complete = *kind != "create"
                    || (matches!(pk.type_, ast::ColumnType::IdUuid { .. })
                        && columns
                            .iter()
                            .all(|c| writable.contains(&c.name) && !ast::has_default_value(c)));
                // SQL also updates the legacy updatedAt column when it has no setter.
                // An explicit scalar/immutable column can still have this server effect.
                let known_update = *kind != "update"
                    || !columns
                        .iter()
                        .any(|c| c.name == "updatedAt" && !writable.contains(&c.name));
                if safe && complete && known_update {
                    let materialized: Vec<_> = columns.iter().map(|c| &c.name).collect();
                    text.push_str(&format!("  predict(input: {input}) {{\n"));
                    if *kind == "create" {
                        text.push_str(&format!("    if (!{}.every(key => Object.prototype.hasOwnProperty.call(input, key))) return null;\n", serde_json::to_string(&materialized).unwrap()));
                    }
                    text.push_str(&format!("    return {{ safe: true as const, kind: {} as const, table: {}, id: input[{}]!, fields: {}, writableFields: {}, materializedFields: {} }};\n  }},\n", json(kind), json(&ast::get_tablename(&table.record.name, &table.record.fields)), json(&pk.name), if *kind == "create" { "input".into() } else { format!("Object.fromEntries(Object.entries(input).filter(([key]) => key !== {}))", json(&pk.name)) }, serde_json::to_string(writable).unwrap(), serde_json::to_string(&materialized).unwrap()));
                }
                let body = match *kind {
                    "create" => format!("create: (input: {input}): Edit<{name}, {result}> => scopedEdit({name}, {operation}, input)"),
                    "update" => format!("update: (id: {input}[{key}], patch: Omit<{input}, {key}>): Edit<{name}, {result}> => {{ if (Object.prototype.hasOwnProperty.call(patch, {key})) throw new Error('InvalidEdit'); return scopedEdit({name}, {operation}, {{ ...patch, [{key}]: id }}); }}", key = json(&pk.name)),
                    _ => format!("delete: (id: {input}[{key}]): Edit<{name}, {result}> => scopedEdit({name}, {operation}, {{ [{key}]: id }})", key = json(&pk.name)),
                };
                records
                    .entry(table.record.name.clone())
                    .or_default()
                    .push(body);
            } else {
                text.push_str(&format!("  decodeResult: (value: unknown) => {metadata}.meta.ReturnData.parse(value),\n"));
                commands.push(format!("{module}: (input: {input}): Edit<{name}, {result}> => scopedEdit({name}, {operation}, input)"));
            }
            text.push_str("});\n");
        }
        text.push_str("export const Records = Object.freeze({\n");
        for (record, methods) in records {
            text.push_str(&format!(
                "  {}: Object.freeze({{ {} }}),\n",
                json(&record),
                methods.join(",\n")
            ));
        }
        text.push_str("});\n");
        text.push_str(&format!("export const Commands = Object.freeze({{ {} }});\nexport const operations = Object.freeze([{}]);\nexport const manifestVersion = {};\n", commands.join(",\n"), operation_bindings.join(", "), json(&version)));
        files.push(generate_text_file(
            core.join("../edits").join(format!("{name}.ts")),
            text,
        ));
        index.push_str(&format!("export * as {name} from './edits/{name}';\n"));
        if groups.len() == 1 {
            index = format!("export * from './edits/{name}';\n");
        }
    }
    files.push(generate_text_file(core.join("../edits.ts"), index));
}

fn json(s: &str) -> String {
    serde_json::to_string(s).unwrap()
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn generated_local_edits_compile_and_execute() {
        let mut schema = ast::Schema::default();
        crate::parser::run(
            "schema.pyre",
            r#"
type Status = Open | Closed { reason String }
record User {
  @public
  key Id.Uuid @id
  name String
  note String?
  reviewer User.key?
  status Json<Status>?
  fixed String @immutable
}
record Audit {
  @public
  id Id.Int @id
  message String
  label String @default("audit")
}
record Token {
  @public
  key Id.Uuid @id
  text String
  updatedAt Int
}
record NullableToken {
  @public
  key Id.Uuid @id
  text String?
  updatedAt Int
}
record DefaultToken {
  @public
  key Id.Uuid @id
  text String @default("default")
  updatedAt Int
}
record PrivateToken {
  @allow(*) { text == "visible" }
  key Id.Uuid @id
  text String
  updatedAt Int
}
record Clock {
  @public
  key Id.Uuid @id
  at DateTime
}
record Marker {
  @public
  key Id.Uuid @id
  text String
  updatedAt Int @immutable
}
record Legacy {
  @public
  id String @id
  value String
}
record Main {
  @public
  id Id.Int @id
}
record Commands {
  @public
  id Id.Int @id
}
record Records {
  @public
  id Id.Int @id
}
"#,
            &mut schema,
        )
        .unwrap();
        let mut database = ast::Database {
            schemas: vec![schema],
        };
        ast::resolve_id_brands(&mut database);
        let context = typecheck::check_schema(&database).unwrap();
        let mut queries = crate::parser::parse_query("commands.pyre", "update Rename($key: User.key, $name: String) { user { @where { key == $key } name = $name } }").unwrap();
        crate::generated_queries::append_generated_crud_queries(&mut queries, &context);
        let info = typecheck::check_queries(&queries, &context).unwrap();
        let root = Path::new(env!("CARGO_MANIFEST_DIR"));
        let out = root.join("target/generated-local-edits");
        std::fs::create_dir_all(&out).unwrap();
        let mut files = Vec::new();
        super::super::core::generate_schema(&context, &database, &out.join("core"), &mut files);
        super::super::core::generate_queries(
            &context,
            &info,
            &queries,
            &out.join("core"),
            &mut files,
        );
        let mut manifest = String::from("import { SessionValidator } from './core/decode';\n");
        let mut entries = Vec::new();
        for def in &queries.queries {
            if let ast::QueryDef::Query(q) = def {
                let module = crate::ext::string::decapitalize(&q.name);
                manifest.push_str(&format!("import {{ meta as {} }} from './core/queries/metadata/{module}';\nimport {{ sql as {}Sql }} from './core/queries/sql/{module}';\n", q.name, q.name));
                entries.push(format!(
                    "[{}.id]: {{ ...{}, sql: {}Sql }}",
                    q.name, q.name, q.name
                ));
            }
        }
        manifest.push_str(&format!("export const manifest = {{ version: 1, manifestVersion: {}, SessionValidator, queries: {{ {} }} }};\n", json(&crate::generate::manifest::fingerprint(&context, &queries, &info)), entries.join(",")));
        files.push(generate_text_file(out.join("manifest.ts"), manifest));
        let edits = files
            .iter()
            .find(|file| file.path.ends_with("edits/Main.ts"))
            .unwrap();
        assert!(edits
            .contents
            .contains("export const Records = Object.freeze"));
        assert!(edits.contents.contains("$metadata0"));
        assert!(edits.contents.contains("$operation0"));
        assert!(!edits.contents.contains("export const User ="));
        assert!(!edits.contents.contains("\"Legacy\": Object.freeze"));
        for record in ["Main", "Commands", "Records"] {
            assert!(edits
                .contents
                .contains(&format!("\"{record}\": Object.freeze")));
        }
        assert!(!edits.contents.contains("RenameOperation"));
        for file in files {
            std::fs::create_dir_all(file.path.parent().unwrap()).unwrap();
            std::fs::write(file.path, file.contents).unwrap();
        }
        std::fs::write(out.join("check.ts"), r#"
import { Main, Records, Commands, batch, type UserId, type AuditId } from './edits';
import type { Database, EditReceipt } from '../../packages/client/src-ts/service/local-edits';
import { namespace, scopedBatch } from '@pyre/core/local-edits';
declare const db: Database<Main>;
declare const id: UserId;
const created = Records.User.create({ key: '00000000-0000-0000-0000-000000000001', name: 'new', fixed: 'x' });
const plan = batch([created, Records.Audit.create({ message: 'audit' }), Records.User.update(id, { note: null }), Records.User.delete(id), Commands.rename({ key: id, name: 'x' })] as const);
const receipt = db.submit(plan);
const empty: EditReceipt<readonly []> = db.submit(batch([]));
receipt.confirmed.then(outcome => { if (outcome.kind === 'confirmed') {
  const user: UserId = outcome.result[0].id;
  const audit: AuditId = outcome.result[1].id;
  // @ts-expect-error distinct IDs
  const wrong: UserId = outcome.result[1].id;
} });
// @ts-expect-error required create field
Records.User.create({ key: id });
// @ts-expect-error integer identity is server generated
Records.Audit.create({ id: 1, message: 'x' });
// @ts-expect-error primary key update
Records.User.update(id, { key: id });
// @ts-expect-error immutable update
Records.User.update(id, { fixed: 'x' });
// @ts-expect-error managed update
Records.User.update(id, { updatedAt: 1 });
// @ts-expect-error nonnullable field
Records.User.update(id, { name: null });
// @ts-expect-error default omission does not allow null
Records.Audit.create({ message: 'x', label: null });
Records.User.update(id, { reviewer: id });
// @ts-expect-error foreign keys share their target identity brand
Records.User.update(id, { reviewer: 'raw' });
// @ts-expect-error whole union replacement requires its members
Records.User.update(id, { status: { _type: 'Closed' } });
// @ts-expect-error existing IDs require schema proof
Records.User.delete('not-an-id');
declare const other: unique symbol;
const Other = namespace<typeof other>('Other', 'm');
const foreign = scopedBatch(Other)([]);
// @ts-expect-error namespace mismatch
db.submit(foreign);
// @ts-expect-error batch is opaque
db.submit({});
// @ts-expect-error batch cannot contain another namespace's plan
batch([foreign]);
"#).unwrap();
        std::fs::write(out.join("tsconfig.json"), r#"{"compilerOptions":{"target":"ES2020","module":"ESNext","moduleResolution":"node","strict":true,"skipLibCheck":true,"esModuleInterop":true,"noEmit":true},"files":["check.ts"]}"#).unwrap();
        let output = std::process::Command::new("node")
            .current_dir(root)
            .args([
                "node_modules/typescript/bin/tsc",
                "-p",
                "target/generated-local-edits/tsconfig.json",
            ])
            .output()
            .unwrap();
        assert!(
            output.status.success(),
            "{}{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
        let output = std::process::Command::new("npm")
            .current_dir(root)
            .env("npm_config_cache", root.join("target/npm-cache"))
            .env("PYRE_GENERATED_EDITS", out.join("edits.ts"))
            .args([
                "exec",
                "--yes",
                "--package=bun@latest",
                "--",
                "bun",
                "test",
                "packages/client/src-ts/service/local-edits.test.ts",
                "--test-name-pattern",
                "real generated builders",
            ])
            .output()
            .unwrap();
        assert!(
            output.status.success(),
            "{}{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
    }
}
