use crate::{
    ast,
    filesystem::{generate_text_file, GeneratedFile},
    typecheck,
};
use std::{
    collections::{BTreeMap, HashMap},
    path::Path,
};

/// Pure descriptors share the compiled query IDs and codecs, never SQL or browser code.
pub fn generate(
    context: &typecheck::Context,
    info: &HashMap<String, typecheck::QueryInfo>,
    queries: &ast::QueryList,
    core: &Path,
    files: &mut Vec<GeneratedFile<String>>,
) {
    let version = crate::generate::manifest::fingerprint(context, queries, info);
    let mut groups: BTreeMap<String, Vec<&ast::Query>> = BTreeMap::new();
    for def in &queries.queries {
        if let ast::QueryDef::Query(q) = def {
            if q.operation != ast::QueryOperation::Query {
                if let Some(i) = info.get(&q.name) {
                    if context.namespace_sync_modes.get(&i.primary_db)
                        != Some(&ast::SyncMode::QueryOnly)
                    {
                        groups.entry(i.primary_db.clone()).or_default().push(q);
                    }
                }
            }
        }
    }
    let ids = super::core::collect_ids(context);
    let outputs = namespace_outputs(&groups, ids.keys());
    let mut index = String::new();
    for (ns, operations) in &groups {
        let (module_name, file_name, name) = outputs.get(ns).expect("namespace output");
        let mut text = String::from("// Generated by Pyre. Pure compiled-operation descriptors.\nimport * as $LocalEdits from '@pyre/core/local-edits';\nimport type * as $Ids from '../core/ids';\n");
        text.push_str(&format!("declare const $namespaceBrand: unique symbol;\nexport type {name} = typeof $namespaceBrand;\nexport const {name} = $LocalEdits.namespace<{name}>({}, {});\nexport const batch = $LocalEdits.scopedBatch({name});\n", json(ns), json(&version)));
        let mut records: BTreeMap<String, Vec<String>> = BTreeMap::new();
        let mut commands = Vec::new();
        for brand in ids.keys() {
            text.push_str(&format!("export type {brand}Id = $Ids.{brand}Id;\n"));
        }
        let mut operation_bindings = Vec::new();
        for (operation_index, q) in operations.iter().enumerate() {
            let module = crate::ext::string::decapitalize(&q.name);
            let metadata = format!("$metadata{operation_index}");
            let input = format!("$input{operation_index}");
            let operation = format!("$operation{operation_index}");
            operation_bindings.push(operation.clone());
            text.push_str(&format!(
                "import * as {metadata} from '../core/queries/metadata/{module}';\n"
            ));
            let table = q.fields.iter().find_map(|f| match f {
                ast::TopLevelQueryField::Field(f) => context.tables.get(&f.name),
                _ => None,
            });
            let generated =
                table.and_then(|t| crate::generated_queries::generated_edit(q, t).map(|g| (t, g)));
            text.push_str(&format!("type {input} = {{\n"));
            for arg in &q.args {
                let reference = if q.generated_crud {
                    table
                        .and_then(|t| {
                            ast::collect_columns(&t.record.fields)
                                .into_iter()
                                .find(|c| c.name == arg.name)
                        })
                        .and_then(|c| {
                            if matches!(c.type_, ast::ColumnType::ForeignKey { .. }) {
                                Some(c.type_.to_string())
                            } else {
                                None
                            }
                        })
                } else {
                    None
                };
                let branded = reference.as_deref().or(arg.type_.as_deref()).and_then(|s| {
                    let ast::ColumnType::ForeignKey {
                        schema,
                        table: target,
                        field,
                        ..
                    } = ast::ColumnType::from_str(s)
                    else {
                        return None;
                    };
                    context
                        .tables
                        .values()
                        .find(|t| {
                            t.record.name.eq_ignore_ascii_case(&target)
                                && schema.as_ref().is_none_or(|s| &t.schema == s)
                        })
                        .and_then(|t| {
                            ast::collect_columns(&t.record.fields)
                                .into_iter()
                                .find(|c| c.name == field)
                                .map(|c| (t, c))
                        })
                        .and_then(|(t, c)| match &c.type_ {
                            ast::ColumnType::Int if ast::is_primary_key(&c) => Some(format!(
                                "{}Id{}",
                                t.record.name,
                                if arg.nullable { " | null" } else { "" }
                            )),
                            ast::ColumnType::IdInt { table }
                            | ast::ColumnType::IdUuid { table } => Some(format!(
                                "{}Id{}",
                                if table.is_empty() {
                                    &t.record.name
                                } else {
                                    table
                                },
                                if arg.nullable { " | null" } else { "" }
                            )),
                            _ => None,
                        })
                });
                let ty = branded.unwrap_or_else(|| {
                    format!(
                        "$LocalEdits.JsonInput<{metadata}.Input[{}]>",
                        json(&arg.name)
                    )
                });
                // Client UUID creation accepts a fresh UUID; references and existing targets remain branded.
                let ty = if generated.as_ref().is_some_and(|(_, (kind, pk, _))| {
                    *kind == "create"
                        && pk.name == arg.name
                        && matches!(pk.type_, ast::ColumnType::IdUuid { .. })
                }) {
                    "string".into()
                } else {
                    ty
                };
                text.push_str(&format!(
                    "  readonly {}{}: {};\n",
                    json(&arg.name),
                    if arg.omittable { "?" } else { "" },
                    ty
                ));
            }
            text.push_str("};\n");
            let result = if let Some((owner, (kind, pk, _))) = &generated {
                let id = match &pk.type_ {
                    ast::ColumnType::Int => format!("{}Id", owner.record.name),
                    ast::ColumnType::IdInt { table } | ast::ColumnType::IdUuid { table } => {
                        format!(
                            "{}Id",
                            if table.is_empty() {
                                &owner.record.name
                            } else {
                                table
                            }
                        )
                    }
                    _ => panic!("unsupported edit identity"),
                };
                format!(
                    "$LocalEdits.{}<{id}>",
                    match *kind {
                        "create" => "Created",
                        "update" => "Updated",
                        _ => "Deleted",
                    }
                )
            } else {
                format!("{metadata}.Result")
            };
            text.push_str(&format!("const {operation}: $LocalEdits.EditOperation<{input}, {result}> = Object.freeze({{\n  id: {metadata}.meta.id,\n  parseInput(value: unknown): {input} {{\n    {metadata}.RawInputValidator.strict().parse(value);\n    {metadata}.meta.InputValidator.strict().parse(value);\n"));
            if let Some((_, (kind, _, writable))) = &generated {
                if *kind == "update" {
                    text.push_str(&format!("    if (!{}.some(key => Object.prototype.hasOwnProperty.call(value, key))) throw new Error('InvalidEdit');\n", serde_json::to_string(writable).unwrap()));
                }
            }
            text.push_str(&format!("    return value as {input};\n  }},\n"));
            if let Some((table, (kind, pk, writable))) = &generated {
                let check = if matches!(pk.type_, ast::ColumnType::IdUuid { .. }) {
                    "typeof id === 'string' && id.length === 36 && /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id)"
                } else {
                    "typeof id === 'number' && Number.isSafeInteger(id)"
                };
                text.push_str(&format!("  decodeResult(value: unknown): {result} {{ const id = (value as any)?.id; if (!({check})) throw new Error('InvalidResult'); return {{ id }} as {result}; }},\n"));
                let columns = ast::collect_columns(&table.record.fields);
                let safe = table.record.fields.iter().any(|f| {
                    matches!(
                        f,
                        ast::Field::FieldDirective(ast::FieldDirective::Permissions(
                            ast::PermissionDetails::Public
                        ))
                    )
                }) && (*kind == "delete"
                    || columns.iter().all(|c| {
                        matches!(
                            c.type_,
                            ast::ColumnType::String
                                | ast::ColumnType::Int
                                | ast::ColumnType::Float
                                | ast::ColumnType::Bool
                                | ast::ColumnType::IdInt { .. }
                                | ast::ColumnType::IdUuid { .. }
                        )
                    }));
                let complete = *kind != "create"
                    || (matches!(pk.type_, ast::ColumnType::IdUuid { .. })
                        && columns
                            .iter()
                            .all(|c| writable.contains(&c.name) && !ast::has_default_value(c)));
                // SQL also updates the legacy updatedAt column when it has no setter.
                // An explicit scalar/immutable column can still have this server effect.
                let known_update = *kind != "update"
                    || !columns
                        .iter()
                        .any(|c| c.name == "updatedAt" && !writable.contains(&c.name));
                if safe && complete && known_update {
                    let materialized: Vec<_> = columns.iter().map(|c| &c.name).collect();
                    text.push_str(&format!("  predict(input: {input}) {{\n"));
                    if *kind == "create" {
                        text.push_str(&format!("    if (!{}.every(key => Object.prototype.hasOwnProperty.call(input, key))) return null;\n", serde_json::to_string(&materialized).unwrap()));
                    }
                    text.push_str(&format!("    return {{ safe: true as const, kind: {} as const, table: {}, id: input[{}]!, fields: {}, writableFields: {}, materializedFields: {} }};\n  }},\n", json(kind), json(&ast::get_tablename(&table.record.name, &table.record.fields)), json(&pk.name), if *kind == "create" { "input".into() } else { format!("Object.fromEntries(Object.entries(input).filter(([key]) => key !== {}))", json(&pk.name)) }, serde_json::to_string(writable).unwrap(), serde_json::to_string(&materialized).unwrap()));
                }
                let body = match *kind {
                    "create" => format!("create: (input: {input}): $LocalEdits.Edit<{name}, {result}> => $LocalEdits.scopedEdit({name}, {operation}, input)"),
                    "update" => format!("update: (id: {input}[{key}], patch: Omit<{input}, {key}>): $LocalEdits.Edit<{name}, {result}> => {{ if (Object.prototype.hasOwnProperty.call(patch, {key})) throw new Error('InvalidEdit'); return $LocalEdits.scopedEdit({name}, {operation}, {{ ...patch, [{key}]: id }}); }}", key = json(&pk.name)),
                    _ => format!("delete: (id: {input}[{key}]): $LocalEdits.Edit<{name}, {result}> => $LocalEdits.scopedEdit({name}, {operation}, {{ [{key}]: id }})", key = json(&pk.name)),
                };
                records
                    .entry(table.record.name.clone())
                    .or_default()
                    .push(body);
            } else {
                text.push_str(&format!("  decodeResult: (value: unknown) => {metadata}.meta.ReturnData.parse(value),\n"));
                commands.push(format!("{module}: (input: {input}): $LocalEdits.Edit<{name}, {result}> => $LocalEdits.scopedEdit({name}, {operation}, input)"));
            }
            text.push_str("});\n");
        }
        text.push_str("export const Records = Object.freeze({\n");
        for (record, methods) in records {
            text.push_str(&format!(
                "  {}: Object.freeze({{ {} }}),\n",
                json(&record),
                methods.join(",\n")
            ));
        }
        text.push_str("});\n");
        text.push_str(&format!("export const Commands = Object.freeze({{ {} }});\nexport const operations = Object.freeze([{}]);\nexport const manifestVersion = {};\n", commands.join(",\n"), operation_bindings.join(", "), json(&version)));
        files.push(generate_text_file(
            core.join("../edits").join(format!("{file_name}.ts")),
            text,
        ));
        index.push_str(&format!(
            "export * as {module_name} from './edits/{file_name}';\n"
        ));
        if groups.len() == 1 {
            index = format!("export * from './edits/{file_name}';\n");
        }
    }
    files.push(generate_text_file(core.join("../edits.ts"), index));
}

fn namespace_outputs<'a>(
    groups: &BTreeMap<String, Vec<&ast::Query>>,
    id_brands: impl Iterator<Item = &'a String>,
) -> BTreeMap<String, (String, String, String)> {
    let mut local_names = std::collections::HashSet::from([
        "Records".to_string(),
        "Commands".to_string(),
        "batch".to_string(),
        "operations".to_string(),
        "manifestVersion".to_string(),
    ]);
    local_names.extend(id_brands.map(|brand| format!("{brand}Id")));

    let mut namespaces: Vec<_> = groups.keys().collect();
    namespaces.sort_by_key(|namespace| {
        if namespace.as_str() == "_default" {
            0
        } else {
            1
        }
    });
    let mut used_modules = std::collections::HashSet::new();
    let mut used_paths = std::collections::HashSet::new();
    let mut outputs = BTreeMap::new();
    for namespace in namespaces {
        let base = if namespace == "_default" {
            "Main".to_string()
        } else {
            typescript_identifier(namespace)
        };
        let module_name =
            unique_generated_name(&base, |candidate| used_modules.contains(candidate));
        used_modules.insert(module_name.clone());
        let file_name = unique_generated_name(&module_name, |candidate| {
            used_paths.contains(&candidate.to_lowercase()) || is_reserved_file_stem(candidate)
        });
        used_paths.insert(file_name.to_lowercase());
        let marker_name = unique_generated_name(&base, |candidate| local_names.contains(candidate));
        outputs.insert(namespace.clone(), (module_name, file_name, marker_name));
    }
    outputs
}

fn typescript_identifier(value: &str) -> String {
    let mut result = String::new();
    for (index, character) in value.chars().enumerate() {
        if character.is_ascii_alphabetic()
            || character == '_'
            || character == '$'
            || (index > 0 && character.is_ascii_digit())
        {
            result.push(character);
        } else {
            result.push_str(&format!("_{:x}_", character as u32));
        }
    }
    result
}

fn is_reserved_file_stem(candidate: &str) -> bool {
    let candidate = candidate.to_ascii_lowercase();
    matches!(candidate.as_str(), "con" | "prn" | "aux" | "nul")
        || candidate
            .strip_prefix("com")
            .or_else(|| candidate.strip_prefix("lpt"))
            .is_some_and(|suffix| {
                matches!(suffix, "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9")
            })
}

fn unique_generated_name(candidate: &str, mut used: impl FnMut(&str) -> bool) -> String {
    let mut result = candidate.to_string();
    while used(&result) {
        result.push_str("Namespace");
    }
    result
}

fn json(s: &str) -> String {
    serde_json::to_string(s).unwrap()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn generate_test_root(database: &ast::Database, out: &Path, authored_queries: &str) {
        let context = typecheck::check_schema(database).unwrap();
        let mut queries = crate::parser::parse_query("queries.pyre", authored_queries).unwrap();
        crate::generated_queries::append_generated_crud_queries(&mut queries, &context);
        let info = typecheck::check_queries(&queries, &context).unwrap();
        let mut files = Vec::new();
        super::super::core::generate_schema(&context, database, &out.join("core"), &mut files);
        super::super::targets::simple::generate_schema(database, out, &mut files);
        super::super::core::generate_queries(
            &context,
            &info,
            &queries,
            &out.join("core"),
            &mut files,
        );
        for file in files {
            std::fs::create_dir_all(file.path.parent().unwrap()).unwrap();
            std::fs::write(file.path, file.contents).unwrap();
        }
    }

    fn typecheck_generated(root: &Path, config: &str) {
        std::fs::write(root.join("tsconfig.json"), config).unwrap();
        let project = root.join("tsconfig.json");
        let output = std::process::Command::new("node")
            .current_dir(Path::new(env!("CARGO_MANIFEST_DIR")))
            .args(["node_modules/typescript/bin/tsc", "-p"])
            .arg(project)
            .output()
            .unwrap();
        assert!(
            output.status.success(),
            "{}{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
    }

    #[test]
    fn generated_ids_are_root_nominal_and_shared_with_query_results() {
        let mut schema = ast::Schema::default();
        crate::parser::run(
            "schema.pyre",
            "record User {\n @public\n id Id.Int @id\n name String\n}\n",
            &mut schema,
        )
        .unwrap();
        let mut database = ast::Database {
            schemas: vec![schema],
        };
        ast::resolve_id_brands(&mut database);

        let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("target/generated-id-roots");
        for output in [root.join("a"), root.join("b")] {
            generate_test_root(
                &database,
                &output,
                "query Users { user { id name } }\nquery UserById($id: User.id) { user { @where { id == $id } id } }",
            );
        }
        assert!(!std::fs::read_to_string(root.join("a/edits/Main.ts"))
            .unwrap()
            .contains("__brand"));
        std::fs::write(
            root.join("check.ts"),
            r#"
import * as A from './a/edits';
import * as B from './b/edits';
import type { Result as AUsers } from './a/core/queries/metadata/users';
import type { Input as AUserById } from './a/core/queries/metadata/userById';
import type { Input as BUserById } from './b/core/queries/metadata/userById';
import type { UserId as ATypesUserId } from './a/types';

declare const result: AUsers;
const id: A.UserId = result.user[0].id;
const publicId: ATypesUserId = id;
const queryInput: AUserById = { id };
A.Records.User.delete(result.user[0].id);
// @ts-expect-error independently generated roots have distinct ID identities
const foreignId: B.UserId = id;
// @ts-expect-error query IDs are rooted in their generated output too
const foreignQueryInput: BUserById = queryInput;
// @ts-expect-error a read ID from one root cannot be edited through another root
B.Records.User.delete(result.user[0].id);
"#,
        )
        .unwrap();
        typecheck_generated(
            &root,
            r#"{"compilerOptions":{"target":"ES2020","module":"ESNext","moduleResolution":"node","strict":true,"skipLibCheck":true,"noEmit":true},"files":["check.ts"]}"#,
        );
    }

    #[test]
    fn namespace_collisions_compile_with_unique_output_paths() {
        let namespace_records = [
            ("_default", "DefaultThing"),
            ("Main", "MainThing"),
            ("Records", "RecordThing"),
            ("Commands", "CommandThing"),
            ("UserId", "User"),
            ("Edit", "EditThing"),
            ("Foo-Bar", "DashedThing"),
            ("CON", "ConThing"),
            ("URL", "UrlUpperThing"),
            ("Url", "UrlThing"),
        ];
        let mut schemas = Vec::new();
        for (namespace, record) in namespace_records {
            let mut schema = ast::Schema::default();
            crate::parser::run(
                &format!("{namespace}/schema.pyre"),
                &format!("record {record} {{\n @public\n id Id.Int @id\n}}\n"),
                &mut schema,
            )
            .unwrap();
            schema.namespace = namespace.to_string();
            schemas.push(schema);
        }
        let mut database = ast::Database { schemas };
        ast::resolve_id_brands(&mut database);
        let context = typecheck::check_schema(&database).unwrap();
        let mut queries = ast::QueryList { queries: vec![] };
        crate::generated_queries::append_generated_crud_queries(&mut queries, &context);
        let info = typecheck::check_queries(&queries, &context).unwrap();
        let root =
            Path::new(env!("CARGO_MANIFEST_DIR")).join("target/generated-namespace-collisions");
        let mut files = Vec::new();
        super::super::core::generate_schema(&context, &database, &root.join("core"), &mut files);
        super::super::core::generate_queries(
            &context,
            &info,
            &queries,
            &root.join("core"),
            &mut files,
        );

        let edit_paths = files
            .iter()
            .filter(|file| file.path.parent() == Some(root.join("edits").as_path()))
            .map(|file| {
                file.path
                    .file_name()
                    .unwrap()
                    .to_string_lossy()
                    .to_lowercase()
            })
            .collect::<Vec<_>>();
        assert_eq!(
            edit_paths.len(),
            edit_paths
                .iter()
                .collect::<std::collections::HashSet<_>>()
                .len()
        );
        let generated = |suffix: &str| {
            &files
                .iter()
                .find(|file| file.path.ends_with(suffix))
                .unwrap_or_else(|| panic!("missing {suffix}"))
                .contents
        };
        assert!(generated("edits/Records.ts").contains("export type RecordsNamespace ="));
        assert!(generated("edits/Commands.ts").contains("export type CommandsNamespace ="));
        assert!(generated("edits/UserId.ts").contains("export type UserIdNamespace ="));
        assert!(generated("edits/Edit.ts").contains("export type Edit ="));
        assert!(generated("edits/Foo_2d_Bar.ts")
            .contains("$LocalEdits.namespace<Foo_2d_Bar>(\"Foo-Bar\""));
        assert!(files
            .iter()
            .any(|file| file.path.ends_with("edits/Main.ts")));
        assert!(files
            .iter()
            .any(|file| file.path.ends_with("edits/MainNamespace.ts")));
        assert!(files
            .iter()
            .any(|file| file.path.ends_with("edits/CONNamespace.ts")));

        for file in files {
            std::fs::create_dir_all(file.path.parent().unwrap()).unwrap();
            std::fs::write(file.path, file.contents).unwrap();
        }
        std::fs::write(
            root.join("check.ts"),
            r#"
import { Records, Commands, UserId, Edit, Foo_2d_Bar, Main, MainNamespace, CON, URL, Url } from './edits';

Records.Records.RecordThing.delete(null as unknown as Records.RecordThingId);
Commands.Records.CommandThing.delete(null as unknown as Commands.CommandThingId);
UserId.Records.User.delete(null as unknown as UserId.UserId);
Edit.Records.EditThing.delete(null as unknown as Edit.EditThingId);
Foo_2d_Bar.Records.DashedThing.delete(null as unknown as Foo_2d_Bar.DashedThingId);
CON.Records.ConThing.delete(null as unknown as CON.ConThingId);
Main.Records.DefaultThing.delete(null as unknown as Main.DefaultThingId);
MainNamespace.Records.MainThing.delete(null as unknown as MainNamespace.MainThingId);
URL.Records.UrlUpperThing.delete(null as unknown as URL.UrlUpperThingId);
Url.Records.UrlThing.delete(null as unknown as Url.UrlThingId);
"#,
        )
        .unwrap();
        typecheck_generated(
            &root,
            r#"{"compilerOptions":{"target":"ES2020","module":"ESNext","moduleResolution":"node","strict":true,"skipLibCheck":true,"noEmit":true},"files":["check.ts"]}"#,
        );
    }

    #[test]
    fn query_only_namespaces_do_not_generate_local_edit_descriptors() {
        let mut query_only = ast::Schema::default();
        crate::parser::run(
            "query-only.pyre",
            "@syncable(false)\nrecord ReadOnly {\n @public\n id Id.Int @id\n}\n",
            &mut query_only,
        )
        .unwrap();
        let mut synced = ast::Schema {
            namespace: "Synced".into(),
            ..ast::Schema::default()
        };
        crate::parser::run(
            "synced.pyre",
            "record Writable {\n @public\n id Id.Int @id\n}\n",
            &mut synced,
        )
        .unwrap();
        let mut database = ast::Database {
            schemas: vec![query_only, synced],
        };
        ast::resolve_id_brands(&mut database);
        let context = typecheck::check_schema(&database).unwrap();
        let mut queries =
            crate::parser::parse_query("queries.pyre", "query ReadOnlyRows { readOnly { id } }\n")
                .unwrap();
        crate::generated_queries::append_generated_crud_queries(&mut queries, &context);
        let info = typecheck::check_queries(&queries, &context).unwrap();
        let root = Path::new("generated");
        let mut files = Vec::new();
        super::super::core::generate_queries(
            &context,
            &info,
            &queries,
            &root.join("core"),
            &mut files,
        );

        assert!(files
            .iter()
            .any(|file| file.path.ends_with("core/queries/metadata/readOnlyRows.ts")));
        assert!(!files
            .iter()
            .any(|file| file.path.ends_with("edits/Main.ts")));
        assert!(files
            .iter()
            .any(|file| file.path.ends_with("edits/Synced.ts")));
        let index = files
            .iter()
            .find(|file| file.path.ends_with("edits.ts"))
            .unwrap();
        assert_eq!(index.contents, "export * from './edits/Synced';\n");
    }

    #[test]
    fn generated_local_edits_compile_and_execute() {
        let mut schema = ast::Schema::default();
        crate::parser::run(
            "schema.pyre",
            r#"
type Status = Open | Closed { reason String }
record User {
  @public
  key Id.Uuid @id
  name String
  note String?
  reviewer User.key?
  status Json<Status>?
  fixed String @immutable
}
record Audit {
  @public
  id Id.Int @id
  message String
  label String @default("audit")
}
record Token {
  @public
  key Id.Uuid @id
  text String
  updatedAt Int
}
record NullableToken {
  @public
  key Id.Uuid @id
  text String?
  updatedAt Int
}
record DefaultToken {
  @public
  key Id.Uuid @id
  text String @default("default")
  updatedAt Int
}
record PrivateToken {
  @allow(*) { text == "visible" }
  key Id.Uuid @id
  text String
  updatedAt Int
}
record Clock {
  @public
  key Id.Uuid @id
  at DateTime
}
record Marker {
  @public
  key Id.Uuid @id
  text String
  updatedAt Int @immutable
}
record Legacy {
  @public
  id String @id
  value String
}
record Main {
  @public
  id Id.Int @id
}
record Commands {
  @public
  id Id.Int @id
}
record Records {
  @public
  id Id.Int @id
}
"#,
            &mut schema,
        )
        .unwrap();
        let mut database = ast::Database {
            schemas: vec![schema],
        };
        ast::resolve_id_brands(&mut database);
        let context = typecheck::check_schema(&database).unwrap();
        let mut queries = crate::parser::parse_query("commands.pyre", "update Rename($key: User.key, $name: String) { user { @where { key == $key } name = $name } }").unwrap();
        crate::generated_queries::append_generated_crud_queries(&mut queries, &context);
        let info = typecheck::check_queries(&queries, &context).unwrap();
        let root = Path::new(env!("CARGO_MANIFEST_DIR"));
        let out = root.join("target/generated-local-edits");
        std::fs::create_dir_all(&out).unwrap();
        let mut files = Vec::new();
        super::super::core::generate_schema(&context, &database, &out.join("core"), &mut files);
        super::super::core::generate_queries(
            &context,
            &info,
            &queries,
            &out.join("core"),
            &mut files,
        );
        let mut manifest = String::from("import { SessionValidator } from './core/decode';\n");
        let mut entries = Vec::new();
        for def in &queries.queries {
            if let ast::QueryDef::Query(q) = def {
                let module = crate::ext::string::decapitalize(&q.name);
                manifest.push_str(&format!("import {{ meta as {} }} from './core/queries/metadata/{module}';\nimport {{ sql as {}Sql }} from './core/queries/sql/{module}';\n", q.name, q.name));
                entries.push(format!(
                    "[{}.id]: {{ ...{}, sql: {}Sql }}",
                    q.name, q.name, q.name
                ));
            }
        }
        manifest.push_str(&format!("export const manifest = {{ version: 1, manifestVersion: {}, SessionValidator, queries: {{ {} }} }};\n", json(&crate::generate::manifest::fingerprint(&context, &queries, &info)), entries.join(",")));
        files.push(generate_text_file(out.join("manifest.ts"), manifest));
        let edits = files
            .iter()
            .find(|file| file.path.ends_with("edits/Main.ts"))
            .unwrap();
        assert!(edits
            .contents
            .contains("export const Records = Object.freeze"));
        assert!(edits.contents.contains("$metadata0"));
        assert!(edits.contents.contains("$operation0"));
        assert!(!edits.contents.contains("export const User ="));
        assert!(!edits.contents.contains("\"Legacy\": Object.freeze"));
        for record in ["Main", "Commands", "Records"] {
            assert!(edits
                .contents
                .contains(&format!("\"{record}\": Object.freeze")));
        }
        assert!(!edits.contents.contains("RenameOperation"));
        for file in files {
            std::fs::create_dir_all(file.path.parent().unwrap()).unwrap();
            std::fs::write(file.path, file.contents).unwrap();
        }
        std::fs::write(out.join("check.ts"), r#"
import { Main, Records, Commands, batch, type UserId, type AuditId } from './edits';
import type { Database, EditReceipt } from '../../packages/client/src-ts/service/local-edits';
import { namespace, scopedBatch } from '@pyre/core/local-edits';
declare const db: Database<Main>;
declare const id: UserId;
const created = Records.User.create({ key: '00000000-0000-0000-0000-000000000001', name: 'new', fixed: 'x' });
const plan = batch([created, Records.Audit.create({ message: 'audit' }), Records.User.update(id, { note: null }), Records.User.delete(id), Commands.rename({ key: id, name: 'x' })] as const);
const receipt = db.submit(plan);
const empty: EditReceipt<readonly []> = db.submit(batch([]));
receipt.confirmed.then(outcome => { if (outcome.kind === 'confirmed') {
  const user: UserId = outcome.result[0].id;
  const audit: AuditId = outcome.result[1].id;
  // @ts-expect-error distinct IDs
  const wrong: UserId = outcome.result[1].id;
} });
// @ts-expect-error required create field
Records.User.create({ key: id });
// @ts-expect-error integer identity is server generated
Records.Audit.create({ id: 1, message: 'x' });
// @ts-expect-error primary key update
Records.User.update(id, { key: id });
// @ts-expect-error immutable update
Records.User.update(id, { fixed: 'x' });
// @ts-expect-error managed update
Records.User.update(id, { updatedAt: 1 });
// @ts-expect-error nonnullable field
Records.User.update(id, { name: null });
// @ts-expect-error default omission does not allow null
Records.Audit.create({ message: 'x', label: null });
Records.User.update(id, { reviewer: id });
// @ts-expect-error foreign keys share their target identity brand
Records.User.update(id, { reviewer: 'raw' });
// @ts-expect-error whole union replacement requires its members
Records.User.update(id, { status: { _type: 'Closed' } });
// @ts-expect-error existing IDs require schema proof
Records.User.delete('not-an-id');
declare const other: unique symbol;
const Other = namespace<typeof other>('Other', 'm');
const foreign = scopedBatch(Other)([]);
// @ts-expect-error namespace mismatch
db.submit(foreign);
// @ts-expect-error batch is opaque
db.submit({});
// @ts-expect-error batch cannot contain another namespace's plan
batch([foreign]);
"#).unwrap();
        std::fs::write(out.join("tsconfig.json"), r#"{"compilerOptions":{"target":"ES2020","module":"ESNext","moduleResolution":"node","strict":true,"skipLibCheck":true,"esModuleInterop":true,"noEmit":true},"files":["check.ts"]}"#).unwrap();
        let output = std::process::Command::new("node")
            .current_dir(root)
            .args([
                "node_modules/typescript/bin/tsc",
                "-p",
                "target/generated-local-edits/tsconfig.json",
            ])
            .output()
            .unwrap();
        assert!(
            output.status.success(),
            "{}{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
        let output = std::process::Command::new("npm")
            .current_dir(root)
            .env("npm_config_cache", root.join("target/npm-cache"))
            .env("PYRE_GENERATED_EDITS", out.join("edits.ts"))
            .args([
                "exec",
                "--yes",
                "--package=bun@latest",
                "--",
                "bun",
                "test",
                "packages/client/src-ts/service/local-edits.test.ts",
                "--test-name-pattern",
                "real generated builders",
            ])
            .output()
            .unwrap();
        assert!(
            output.status.success(),
            "{}{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
    }
}
