use crate::ephemeral::{Contract, StateContract, TaggedUnion, ValueSchema, ValueType};
use crate::filesystem::{generate_text_file, GeneratedFile};
use crate::generate::server::rust::{to_field_name, to_pascal_name};
use crate::typecheck;
use std::path::Path;

pub fn generate(
    context: &typecheck::Context,
    typescript_out_dir: &Path,
    rust_out_dir: &Path,
    files: &mut Vec<GeneratedFile<String>>,
) {
    if context.states.is_empty() {
        return;
    }

    let contract = Contract::from_context(context)
        .expect("typechecked ephemeral state should always produce a contract");
    files.push(generate_text_file(
        typescript_out_dir.join("state.ts"),
        typescript_state(&contract),
    ));
    files.push(generate_text_file(
        rust_out_dir.join("state.rs"),
        rust_state(&contract),
    ));
}

fn typescript_state(contract: &Contract) -> String {
    let mut result = String::from("// This file is generated by Pyre. Do not edit by hand.\n\n");

    for (name, definition) in &contract.types {
        result.push_str(&typescript_union(name, definition));
    }
    if let Some(state) = &contract.connection {
        result.push_str(&typescript_state_types("Connection", state));
    }
    if let Some(state) = &contract.shared {
        result.push_str(&typescript_state_types("Shared", state));
    }

    result.push_str("export interface StateTypes {\n");
    if contract.connection.is_some() {
        result.push_str("  connection: Connection;\n  connectionPatch: ConnectionPatch;\n");
    } else {
        result.push_str(
            "  connection: Record<string, never>;\n  connectionPatch: Record<string, never>;\n",
        );
    }
    if contract.shared.is_some() {
        result.push_str("  shared: Shared;\n  sharedPatch: SharedPatch;\n");
    } else {
        result
            .push_str("  shared: Record<string, never>;\n  sharedPatch: Record<string, never>;\n");
    }
    result.push_str("}\n\n");

    result.push_str("export const stateMetadata = {\n");
    if let Some(state) = &contract.connection {
        result.push_str(&typescript_metadata("Connection", state));
    }
    if let Some(state) = &contract.shared {
        result.push_str(&typescript_metadata("Shared", state));
    }
    result.push_str("} as const;\n\n");
    result.push_str("export type StateName = keyof typeof stateMetadata;\n");
    result
}

fn typescript_union(name: &str, definition: &TaggedUnion) -> String {
    let mut result = format!("export type {name} =\n");
    for (variant, fields) in &definition.variants {
        result.push_str(&format!("  | {{ _type: {variant:?}"));
        for (field, schema) in fields {
            result.push_str(&format!("; {field}: {}", typescript_type(schema)));
        }
        result.push_str(" }\n");
    }
    result.push_str(";\n\n");
    result
}

fn typescript_state_types(name: &str, state: &StateContract) -> String {
    let mut result = format!("export interface {name} {{\n");
    for (field, contract) in &state.fields {
        result.push_str(&format!(
            "  {field}: {};\n",
            typescript_type(&contract.schema)
        ));
    }
    result.push_str("}\n\n");

    result.push_str(&format!("export interface {name}Patch {{\n"));
    for (field, contract) in &state.fields {
        if contract.writable {
            result.push_str(&format!(
                "  {field}?: {};\n",
                typescript_type(&contract.schema)
            ));
        }
    }
    result.push_str("}\n\n");
    result
}

fn typescript_type(schema: &ValueSchema) -> String {
    let base = match &schema.type_ {
        ValueType::String | ValueType::Date | ValueType::IdUuid => "string".to_string(),
        ValueType::Int | ValueType::Float | ValueType::IdInt => "number".to_string(),
        ValueType::Bool => "boolean".to_string(),
        ValueType::DateTime => "Date".to_string(),
        ValueType::Json => "unknown".to_string(),
        ValueType::TypedJson { value } => typescript_type(value),
        ValueType::List { item } => format!("Array<{}>", typescript_type(item)),
        ValueType::Dict { value } => format!("Record<string, {}>", typescript_type(value)),
        ValueType::Custom { name } => name.clone(),
    };
    if schema.nullable {
        format!("{base} | null")
    } else {
        base
    }
}

fn typescript_metadata(name: &str, state: &StateContract) -> String {
    let writable = state
        .fields
        .iter()
        .filter(|(_, field)| field.writable)
        .map(|(name, _)| format!("{name:?}"))
        .collect::<Vec<_>>()
        .join(", ");
    let derived = state
        .fields
        .iter()
        .filter(|(_, field)| !field.writable)
        .map(|(name, _)| format!("{name:?}"))
        .collect::<Vec<_>>()
        .join(", ");
    format!("  {name}: {{ writableFields: [{writable}], derivedFields: [{derived}] }},\n")
}

fn rust_state(contract: &Contract) -> String {
    let mut result = String::from("// This file is generated by Pyre. Do not edit by hand.\n\n");
    result.push_str("#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]\n");
    result.push_str("#[serde(untagged)]\n");
    result.push_str("pub enum DateTime {\n    UnixSeconds(i64),\n    Text(String),\n}\n\n");
    result.push_str("#[derive(Clone, Debug, Default, PartialEq)]\n");
    result.push_str("pub enum PatchField<T> {\n");
    result.push_str("    #[default]\n");
    result.push_str("    Omitted,\n");
    result.push_str("    Value(T),\n");
    result.push_str("}\n\n");
    result.push_str("impl<T> PatchField<T> {\n");
    result.push_str("    pub fn is_omitted(&self) -> bool {\n");
    result.push_str("        matches!(self, Self::Omitted)\n");
    result.push_str("    }\n");
    result.push_str("}\n\n");
    result.push_str("impl<T: serde::Serialize> serde::Serialize for PatchField<T> {\n");
    result.push_str("    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {\n");
    result.push_str("        match self {\n");
    result.push_str("            Self::Omitted => serializer.serialize_unit(),\n");
    result.push_str("            Self::Value(value) => value.serialize(serializer),\n");
    result.push_str("        }\n");
    result.push_str("    }\n");
    result.push_str("}\n\n");
    result.push_str(
        "impl<'de, T: serde::Deserialize<'de>> serde::Deserialize<'de> for PatchField<T> {\n",
    );
    result.push_str("    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {\n");
    result.push_str("        T::deserialize(deserializer).map(Self::Value)\n");
    result.push_str("    }\n");
    result.push_str("}\n\n");

    for (name, definition) in &contract.types {
        result.push_str(&rust_union(name, definition));
    }
    if let Some(state) = &contract.connection {
        result.push_str(&rust_state_types("Connection", state));
    }
    if let Some(state) = &contract.shared {
        result.push_str(&rust_state_types("Shared", state));
    }

    result.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    result.push_str("pub struct StateMetadata {\n");
    result.push_str("    pub writable_fields: &'static [&'static str],\n");
    result.push_str("    pub derived_fields: &'static [&'static str],\n");
    result.push_str("}\n\n");
    if let Some(state) = &contract.connection {
        result.push_str(&rust_metadata("CONNECTION_METADATA", state));
    }
    if let Some(state) = &contract.shared {
        result.push_str(&rust_metadata("SHARED_METADATA", state));
    }
    result
}

fn rust_union(name: &str, definition: &TaggedUnion) -> String {
    let mut result = String::from(
        "#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]\n#[serde(tag = \"_type\")]\n",
    );
    result.push_str(&format!("pub enum {} {{\n", to_pascal_name(name)));
    for (variant, fields) in &definition.variants {
        result.push_str(&format!("    #[serde(rename = {variant:?})]\n"));
        let variant_name = to_pascal_name(variant);
        if fields.is_empty() {
            result.push_str(&format!("    {variant_name},\n"));
            continue;
        }
        result.push_str(&format!("    {variant_name} {{\n"));
        for (field, schema) in fields {
            let rust_field = to_field_name(field);
            if rust_field != *field {
                result.push_str(&format!("        #[serde(rename = {field:?})]\n"));
            }
            result.push_str(&format!("        {rust_field}: {},\n", rust_type(schema)));
        }
        result.push_str("    },\n");
    }
    result.push_str("}\n\n");
    result
}

fn rust_state_types(name: &str, state: &StateContract) -> String {
    let mut result =
        String::from("#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]\n");
    result.push_str(&format!("pub struct {name} {{\n"));
    for (field, contract) in &state.fields {
        result.push_str(&rust_struct_field(
            field,
            &rust_type(&contract.schema),
            false,
        ));
    }
    result.push_str("}\n\n");

    result.push_str(
        "#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]\n",
    );
    result.push_str(&format!("pub struct {name}Patch {{\n"));
    for (field, contract) in &state.fields {
        if contract.writable {
            result.push_str(&rust_struct_field(
                field,
                &format!("PatchField<{}>", rust_type(&contract.schema)),
                true,
            ));
        }
    }
    result.push_str("}\n\n");
    result
}

fn rust_struct_field(name: &str, type_: &str, optional: bool) -> String {
    let rust_name = to_field_name(name);
    let mut result = String::new();
    if rust_name != name || optional {
        result.push_str("    #[serde(");
        if rust_name != name {
            result.push_str(&format!("rename = {name:?}"));
            if optional {
                result.push_str(", ");
            }
        }
        if optional {
            result.push_str("default, skip_serializing_if = \"PatchField::is_omitted\"");
        }
        result.push_str(")]\n");
    }
    result.push_str(&format!("    pub {rust_name}: {type_},\n"));
    result
}

fn rust_type(schema: &ValueSchema) -> String {
    let base = match &schema.type_ {
        ValueType::String | ValueType::Date | ValueType::IdUuid => "String".to_string(),
        ValueType::Int | ValueType::IdInt => "i64".to_string(),
        ValueType::Float => "f64".to_string(),
        ValueType::Bool => "bool".to_string(),
        ValueType::DateTime => "DateTime".to_string(),
        ValueType::Json => "serde_json::Value".to_string(),
        ValueType::TypedJson { value } => rust_type(value),
        ValueType::List { item } => format!("Vec<{}>", rust_type(item)),
        ValueType::Dict { value } => {
            format!("std::collections::HashMap<String, {}>", rust_type(value))
        }
        ValueType::Custom { name } => to_pascal_name(name),
    };
    if schema.nullable {
        format!("Option<{base}>")
    } else {
        base
    }
}

fn rust_metadata(name: &str, state: &StateContract) -> String {
    let fields = |writable| {
        state
            .fields
            .iter()
            .filter(|(_, field)| field.writable == writable)
            .map(|(name, _)| format!("{name:?}"))
            .collect::<Vec<_>>()
            .join(", ")
    };
    format!(
        "pub const {name}: StateMetadata = StateMetadata {{\n    writable_fields: &[{}],\n    derived_fields: &[{}],\n}};\n\n",
        fields(true),
        fields(false)
    )
}
