use crate::ast;
use crate::ext::string;
use crate::filesystem;
use crate::filesystem::generate_text_file;
use crate::generate::typealias;
use crate::typecheck;
use std::collections::{HashMap, HashSet};
use std::path::Path;

pub fn generate_schema(
    context: &typecheck::Context,
    database: &ast::Database,
    base_out_dir: &Path,
    files: &mut Vec<filesystem::GeneratedFile<String>>,
) {
    let mut result = String::new();
    result.push_str("// This file is generated by Pyre. Do not edit by hand.\n\n");
    let mut used_modules = HashSet::new();
    for schema in &database.schemas {
        let module = unique_name(&to_snake_name(&schema.namespace), &mut used_modules);
        let source = crate::generate::to_string::standalone_schema_to_string(context, schema);
        result.push_str(&format!("pub mod {module} {{\n"));
        result.push_str(&format!(
            "    pub const NAME: &str = {:?};\n",
            schema.namespace
        ));
        result.push_str(&format!(
            "    pub const SCHEMA_SOURCE: &str = {:?};\n\n",
            source
        ));
        result.push_str("    pub async fn ensure_database(\n");
        result.push_str("        conn: &libsql::Connection,\n");
        result.push_str("    ) -> Result<pyre::server::schema::EnsureDatabaseOutcome, pyre::server::schema::EnsureDatabaseError> {\n");
        result.push_str(
            "        pyre::server::schema::ensure_database(conn, NAME, SCHEMA_SOURCE).await\n",
        );
        result.push_str("    }\n");
        result.push_str("}\n\n");
    }

    files.push(generate_text_file(
        base_out_dir.join("databases.rs"),
        result,
    ));
    files.push(generate_text_file(
        base_out_dir.join("seed.rs"),
        to_seed_file(context, database),
    ));
}

fn to_seed_file(context: &typecheck::Context, database: &ast::Database) -> String {
    let mut result = String::new();
    result.push_str("// This file is generated by Pyre. Do not edit by hand.\n\n");

    if database.schemas.len() == 1 {
        let namespace = &database.schemas[0].namespace;
        let mut tables = context
            .tables
            .values()
            .filter(|table| &table.schema == namespace)
            .collect::<Vec<_>>();
        tables.sort_by_key(|table| ast::get_tablename(&table.record.name, &table.record.fields));
        result.push_str(&to_seed_scope(context, &tables));
        return result;
    }

    let mut used_modules = HashSet::new();
    for schema in &database.schemas {
        let module = unique_name(&to_snake_name(&schema.namespace), &mut used_modules);
        let mut tables = context
            .tables
            .values()
            .filter(|table| table.schema == schema.namespace)
            .collect::<Vec<_>>();
        tables.sort_by_key(|table| ast::get_tablename(&table.record.name, &table.record.fields));
        result.push_str(&format!("pub mod {module} {{\n"));
        for line in to_seed_scope(context, &tables).lines() {
            result.push_str("    ");
            result.push_str(line);
            result.push('\n');
        }
        result.push_str("}\n\n");
    }

    result
}

fn to_seed_scope(context: &typecheck::Context, tables: &[&typecheck::Table]) -> String {
    let mut result = String::new();
    result.push_str("#[derive(Clone, Debug, serde::Serialize)]\n");
    result.push_str("#[serde(untagged)]\n");
    result.push_str("pub enum DateTime {\n");
    result.push_str("    UnixSeconds(i64),\n");
    result.push_str("    Text(String),\n");
    result.push_str("}\n\n");
    result.push_str("#[derive(Clone, Debug, Default)]\n");
    result.push_str("pub enum SeedField<T> {\n");
    result.push_str("    #[default]\n");
    result.push_str("    Omitted,\n");
    result.push_str("    Null,\n");
    result.push_str("    Value(T),\n");
    result.push_str("}\n\n");
    result.push_str("impl<T> SeedField<T> {\n");
    result.push_str("    pub fn is_omitted(&self) -> bool {\n");
    result.push_str("        matches!(self, Self::Omitted)\n");
    result.push_str("    }\n");
    result.push_str("}\n\n");
    result.push_str("impl<T: serde::Serialize> serde::Serialize for SeedField<T> {\n");
    result.push_str("    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {\n");
    result.push_str("        match self {\n");
    result.push_str("            Self::Omitted => serializer.serialize_unit(),\n");
    result.push_str("            Self::Null => serializer.serialize_none(),\n");
    result.push_str("            Self::Value(value) => value.serialize(serializer),\n");
    result.push_str("        }\n");
    result.push_str("    }\n");
    result.push_str("}\n\n");
    result.push_str(&seed_custom_types(context));

    for table in tables {
        let table_name = ast::get_tablename(&table.record.name, &table.record.fields);
        result.push_str("#[derive(Clone, Debug, Default, serde::Serialize)]\n");
        result.push_str(&format!("pub struct {} {{\n", seed_row_name(&table_name)));
        for column in ast::collect_columns(&table.record.fields) {
            let field_name = to_field_name(&column.name);
            result.push_str(&format!("    #[serde(rename = {:?}", column.name));
            if column.nullable || matches!(column.type_, ast::ColumnType::Nullable(_)) {
                result.push_str(", skip_serializing_if = \"SeedField::is_omitted\")]\n");
                result.push_str(&format!(
                    "    pub {}: SeedField<{}>,\n",
                    field_name,
                    seed_rust_type(&column.type_)
                ));
            } else {
                result.push_str(", skip_serializing_if = \"Option::is_none\")]\n");
                result.push_str(&format!(
                    "    pub {}: Option<{}>,\n",
                    field_name,
                    seed_rust_type(&column.type_)
                ));
            }
        }
        for link in ast::collect_links(&table.record.fields) {
            let linked_table = typecheck::get_linked_table(context, &link).expect(
                "typechecked links should always reference a table while generating seed types",
            );
            let linked_table_name =
                ast::get_tablename(&linked_table.record.name, &linked_table.record.fields);
            if linked_table.schema != table.schema {
                continue;
            }
            let primary_key = ast::get_primary_id_field_name(&table.record.fields);
            let parent_to_child = link
                .local_ids
                .iter()
                .all(|field| primary_key.as_ref() == Some(field));
            let link_type = if parent_to_child {
                format!("Vec<{}>", seed_row_name(&linked_table_name))
            } else {
                format!("Box<{}>", seed_row_name(&linked_table_name))
            };
            result.push_str(&format!(
                "    #[serde(rename = {:?}, skip_serializing_if = \"Option::is_none\")]\n",
                link.link_name
            ));
            result.push_str(&format!(
                "    pub {}: Option<{}>,\n",
                to_field_name(&link.link_name),
                link_type
            ));
        }
        result.push_str("}\n\n");
    }

    result.push_str("#[derive(Clone, Debug, Default, serde::Serialize)]\n");
    result.push_str("pub struct SeedInput {\n");
    for table in tables {
        let table_name = ast::get_tablename(&table.record.name, &table.record.fields);
        result.push_str(&format!(
            "    #[serde(rename = {:?}, skip_serializing_if = \"Option::is_none\")]\n",
            table_name
        ));
        result.push_str(&format!(
            "    pub {}: Option<Vec<{}>>,\n",
            to_field_name(&table_name),
            seed_row_name(&table_name)
        ));
    }
    result.push_str("}\n\n");
    result.push_str("pub async fn seed(\n");
    result.push_str("    conn: &libsql::Connection,\n");
    result.push_str("    input: SeedInput,\n");
    result.push_str(") -> Result<pyre::server::seed::SeedResult, pyre::server::seed::Error> {\n");
    result.push_str("    pyre::server::seed::seed(conn, input).await\n");
    result.push_str("}\n");
    result
}

fn seed_row_name(table_name: &str) -> String {
    format!("Seed{}Row", to_pascal_name(table_name))
}

fn seed_rust_type(type_: &ast::ColumnType) -> String {
    match type_ {
        ast::ColumnType::String | ast::ColumnType::Date => "String".to_string(),
        ast::ColumnType::DateTime => "DateTime".to_string(),
        ast::ColumnType::Int | ast::ColumnType::IdInt { .. } => "i64".to_string(),
        ast::ColumnType::IdUuid { .. } => "String".to_string(),
        ast::ColumnType::ForeignKey {
            serialization_type, ..
        } => seed_concrete_rust_type(
            serialization_type
                .as_ref()
                .unwrap_or(&ast::ConcreteSerializationType::Integer),
        ),
        ast::ColumnType::Float => "f64".to_string(),
        ast::ColumnType::Bool => "bool".to_string(),
        ast::ColumnType::Json => "serde_json::Value".to_string(),
        ast::ColumnType::JsonTyped(inner) => seed_rust_type(inner),
        ast::ColumnType::List(inner) => format!("Vec<{}>", seed_rust_type(inner)),
        ast::ColumnType::Dict(inner) => format!(
            "std::collections::HashMap<String, {}>",
            seed_rust_type(inner)
        ),
        ast::ColumnType::Nullable(inner) => seed_rust_type(inner),
        ast::ColumnType::Custom(name) => format!("Seed{}", to_pascal_name(name)),
    }
}

fn seed_concrete_rust_type(type_: &ast::ConcreteSerializationType) -> String {
    match type_ {
        ast::ConcreteSerializationType::Integer | ast::ConcreteSerializationType::IdInt => {
            "i64".to_string()
        }
        ast::ConcreteSerializationType::Real => "f64".to_string(),
        ast::ConcreteSerializationType::Text
        | ast::ConcreteSerializationType::Date
        | ast::ConcreteSerializationType::IdUuid => "String".to_string(),
        ast::ConcreteSerializationType::DateTime => "DateTime".to_string(),
        ast::ConcreteSerializationType::JsonB => "serde_json::Value".to_string(),
        ast::ConcreteSerializationType::Blob
        | ast::ConcreteSerializationType::VectorBlob { .. } => "Vec<u8>".to_string(),
    }
}

fn seed_custom_types(context: &typecheck::Context) -> String {
    let mut types = context
        .types
        .iter()
        .filter_map(|(name, (definition, type_))| match (definition, type_) {
            (crate::error::DefInfo::Def(_), typecheck::Type::OneOf { variants }) => {
                Some((name, variants))
            }
            _ => None,
        })
        .collect::<Vec<_>>();
    types.sort_by(|(left, _), (right, _)| left.cmp(right));

    let mut result = String::new();
    for (name, variants) in types {
        result.push_str("#[derive(Clone, Debug, serde::Serialize)]\n");
        result.push_str("#[serde(tag = \"_type\")]\n");
        result.push_str(&format!("pub enum Seed{} {{\n", to_pascal_name(name)));
        for variant in variants {
            result.push_str(&format!("    #[serde(rename = {:?})]\n", variant.name));
            let variant_name = to_pascal_name(&variant.name);
            match &variant.fields {
                None => result.push_str(&format!("    {},\n", variant_name)),
                Some(fields) => {
                    result.push_str(&format!("    {} {{\n", variant_name));
                    for field in fields {
                        let ast::Field::Column(column) = field else {
                            continue;
                        };
                        result.push_str(&format!("        #[serde(rename = {:?}", column.name));
                        if column.nullable || matches!(column.type_, ast::ColumnType::Nullable(_)) {
                            result
                                .push_str(", skip_serializing_if = \"SeedField::is_omitted\")]\n");
                            result.push_str(&format!(
                                "        {}: SeedField<{}>,\n",
                                to_field_name(&column.name),
                                seed_rust_type(&column.type_)
                            ));
                        } else {
                            result.push_str(")]\n");
                            result.push_str(&format!(
                                "        {}: {},\n",
                                to_field_name(&column.name),
                                seed_rust_type(&column.type_)
                            ));
                        }
                    }
                    result.push_str("    },\n");
                }
            }
        }
        result.push_str("}\n\n");
    }
    result
}

pub fn generate_queries(
    context: &typecheck::Context,
    query_list: &ast::QueryList,
    base_out_dir: &Path,
    files: &mut Vec<filesystem::GeneratedFile<String>>,
) {
    files.push(generate_text_file(
        base_out_dir.join("server.rs"),
        to_server_file(context, query_list),
    ));
}

fn to_server_file(context: &typecheck::Context, query_list: &ast::QueryList) -> String {
    let queries = query_list
        .queries
        .iter()
        .filter_map(|query_def| match query_def {
            ast::QueryDef::Query(query) => Some(query),
            _ => None,
        })
        .collect::<Vec<_>>();

    let mut result = String::new();
    result.push_str("// This file is generated by Pyre. Do not edit by hand.\n");
    result.push_str("\n");
    result.push_str("pub type DecodeError = serde_path_to_error::Error<serde_json::Error>;\n");
    result.push_str("\n");
    result.push_str("fn decode_json<T: serde::de::DeserializeOwned>(\n");
    result.push_str("    value: serde_json::Value,\n");
    result.push_str(") -> Result<T, DecodeError> {\n");
    result.push_str("    let json = value.to_string();\n");
    result.push_str("    let mut deserializer = serde_json::Deserializer::from_str(&json);\n");
    result.push_str("    serde_path_to_error::deserialize(&mut deserializer)\n");
    result.push_str("}\n");
    result.push_str("\n");
    result.push_str("#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]\n");
    result.push_str("#[serde(untagged)]\n");
    result.push_str("pub enum DateTime {\n");
    result.push_str("    UnixSeconds(i64),\n");
    result.push_str("    Text(String),\n");
    result.push_str("}\n");
    result.push_str("\n");
    result.push_str(&custom_types(context));
    result.push_str("\n");
    result.push_str("#[derive(Clone, Debug, Default)]\n");
    result.push_str("pub enum OptionalField<T> {\n");
    result.push_str("    #[default]\n");
    result.push_str("    Omitted,\n");
    result.push_str("    Null,\n");
    result.push_str("    Value(T),\n");
    result.push_str("}\n");
    result.push_str("\n");
    result.push_str("impl<T> OptionalField<T> {\n");
    result.push_str("    pub fn is_omitted(&self) -> bool {\n");
    result.push_str("        matches!(self, Self::Omitted)\n");
    result.push_str("    }\n");
    result.push_str("}\n");
    result.push_str("\n");
    result.push_str("impl<T: serde::Serialize> serde::Serialize for OptionalField<T> {\n");
    result.push_str("    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {\n");
    result.push_str("        match self {\n");
    result.push_str("            Self::Omitted => serializer.serialize_unit(),\n");
    result.push_str("            Self::Null => serializer.serialize_none(),\n");
    result.push_str("            Self::Value(value) => value.serialize(serializer),\n");
    result.push_str("        }\n");
    result.push_str("    }\n");
    result.push_str("}\n");
    result.push_str("\n");

    result.push_str("pub mod query_ids {\n");
    let mut used_constants = HashSet::new();
    for query in &queries {
        let constant = unique_name(&to_constant_name(&query.name), &mut used_constants);
        result.push_str(&format!(
            "    pub const {}: &str = {:?};\n",
            constant, query.interface_hash
        ));
    }
    result.push_str("}\n");
    result.push_str("\n");

    let mut used_modules = HashSet::new();
    let mut used_aliases = HashSet::new();
    for query in &queries {
        let module = unique_name(&to_snake_name(&query.name), &mut used_modules);
        let pascal = unique_name(&to_pascal_name(&query.name), &mut used_aliases);
        result.push_str(&query_module(context, query, &module));
        result.push_str("\n");
        result.push_str(&format!("pub type {}Input = {}::Input;\n", pascal, module));
        result.push_str(&format!(
            "pub type {}Output = {}::Output;\n",
            pascal, module
        ));
        result.push_str("\n");
    }

    result
}

fn query_module(context: &typecheck::Context, query: &ast::Query, module: &str) -> String {
    let mut result = String::new();
    result.push_str(&format!("pub mod {} {{\n", module));
    result.push_str("    use super::*;\n");
    result.push_str("\n");
    result.push_str(&format!(
        "    pub const ID: &str = {:?};\n",
        query.interface_hash
    ));
    result.push_str("\n");
    result.push_str(&input_struct(context, query));
    result.push_str("\n");
    result.push_str(&output_structs(context, query));
    result.push_str("\n");
    result.push_str("    impl TryFrom<serde_json::Value> for Output {\n");
    result.push_str("        type Error = DecodeError;\n");
    result.push_str("\n");
    result
        .push_str("        fn try_from(value: serde_json::Value) -> Result<Self, Self::Error> {\n");
    result.push_str("            decode_json(value)\n");
    result.push_str("        }\n");
    result.push_str("    }\n");
    result.push_str("}\n");
    result
}

fn input_struct(context: &typecheck::Context, query: &ast::Query) -> String {
    let mut result = String::new();
    result.push_str("    #[derive(Clone, Debug, serde::Serialize)]\n");
    result.push_str("    pub struct Input {\n");

    for arg in &query.args {
        let field_name = to_field_name(&arg.name);
        if field_name != arg.name {
            result.push_str(&format!("        #[serde(rename = {:?})]\n", arg.name));
        }
        if arg.omittable {
            if arg.nullable {
                result.push_str(
                    "        #[serde(skip_serializing_if = \"OptionalField::is_omitted\")]\n",
                );
                result.push_str(&format!(
                    "        pub {}: OptionalField<{}>,\n",
                    field_name,
                    rust_type(resolve_arg_type(context, arg).as_deref())
                ));
            } else {
                result.push_str("        #[serde(skip_serializing_if = \"Option::is_none\")]\n");
                result.push_str(&format!(
                    "        pub {}: Option<{}>,\n",
                    field_name,
                    rust_type(resolve_arg_type(context, arg).as_deref())
                ));
            }
        } else if arg.nullable {
            result.push_str(&format!(
                "        pub {}: Option<{}>,\n",
                field_name,
                rust_type(resolve_arg_type(context, arg).as_deref())
            ));
        } else {
            result.push_str(&format!(
                "        pub {}: {},\n",
                field_name,
                rust_type(resolve_arg_type(context, arg).as_deref())
            ));
        }
    }

    result.push_str("    }\n");
    result.push_str("\n");
    result.push_str("    impl Input {\n");
    result.push_str("        pub fn into_json(self) -> serde_json::Value {\n");
    result.push_str("            serde_json::to_value(self).expect(\"generated Pyre input should serialize\")\n");
    result.push_str("        }\n");
    result.push_str("    }\n");
    result
}

fn resolve_arg_type(
    context: &typecheck::Context,
    arg: &ast::QueryParamDefinition,
) -> Option<String> {
    arg.type_
        .as_deref()
        .map(|type_| typecheck::resolve_query_param_type(context, type_))
}

fn output_structs(context: &typecheck::Context, query: &ast::Query) -> String {
    let formatter = typealias::TypeFormatter {
        to_comment: Box::new(|_| String::new()),
        to_type_def_start: Box::new(|name| {
            let name = if name == "ReturnData" {
                "Output".to_string()
            } else {
                to_pascal_name(name)
            };
            format!(
                "    #[derive(Clone, Debug, serde::Deserialize)]\n    pub struct {} {{\n",
                name
            )
        }),
        to_field: Box::new(|name, type_, metadata| {
            let field_name = to_field_name(name);
            let mut result = String::new();
            if field_name != name {
                result.push_str(&format!("        #[serde(rename = {:?})]\n", name));
            }
            result.push_str(&format!(
                "        pub {}: {},",
                field_name,
                output_rust_type(type_, metadata)
            ));
            result
        }),
        to_type_def_end: Box::new(|| "    }\n".to_string()),
        to_field_separator: Box::new(|_| "\n".to_string()),
    };

    let mut result = String::new();
    typealias::return_data_aliases(context, query, &mut result, &formatter);
    result.trim_end().to_string()
}

fn output_rust_type(type_: &str, metadata: typealias::FieldMetadata) -> String {
    let type_ = if metadata.is_link {
        to_pascal_name(type_)
    } else {
        rust_type(Some(type_))
    };

    if metadata.is_array_relationship {
        format!("Vec<{}>", type_)
    } else if metadata.is_optional {
        format!("Option<{}>", type_)
    } else {
        type_
    }
}

fn rust_type(type_: Option<&str>) -> String {
    match type_.map(ast::ColumnType::from_str) {
        Some(ast::ColumnType::String) => "String".to_string(),
        Some(ast::ColumnType::DateTime) => "DateTime".to_string(),
        Some(ast::ColumnType::Date) => "String".to_string(),
        Some(ast::ColumnType::Int)
        | Some(ast::ColumnType::IdInt { .. })
        | Some(ast::ColumnType::ForeignKey { .. }) => "i64".to_string(),
        Some(ast::ColumnType::IdUuid { .. }) => "String".to_string(),
        Some(ast::ColumnType::Float) => "f64".to_string(),
        Some(ast::ColumnType::Bool) => "bool".to_string(),
        Some(ast::ColumnType::Json) => "serde_json::Value".to_string(),
        Some(ast::ColumnType::JsonTyped(inner)) => rust_type_for_column(&inner),
        Some(ast::ColumnType::List(inner)) => {
            format!("Vec<{}>", rust_type_for_column(&inner))
        }
        Some(ast::ColumnType::Dict(inner)) => {
            format!(
                "std::collections::HashMap<String, {}>",
                rust_type_for_column(&inner)
            )
        }
        Some(ast::ColumnType::Nullable(inner)) => {
            format!("Option<{}>", rust_type_for_column(&inner))
        }
        Some(ast::ColumnType::Custom(name)) => to_pascal_name(&name),
        _ => "serde_json::Value".to_string(),
    }
}

fn rust_type_for_column(type_: &ast::ColumnType) -> String {
    rust_type(Some(&type_.to_string()))
}

fn custom_types(context: &typecheck::Context) -> String {
    let mut types = context
        .types
        .iter()
        .filter_map(|(name, (definition, type_))| match (definition, type_) {
            (crate::error::DefInfo::Def(_), typecheck::Type::OneOf { variants }) => {
                Some((name, variants))
            }
            _ => None,
        })
        .collect::<Vec<_>>();
    types.sort_by(|(left, _), (right, _)| left.cmp(right));

    let mut result = String::new();
    for (name, variants) in types {
        result.push_str("#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]\n");
        result.push_str("#[serde(tag = \"_type\")]\n");
        result.push_str(&format!("pub enum {} {{\n", to_pascal_name(name)));
        for variant in variants {
            result.push_str(&format!("    #[serde(rename = {:?})]\n", variant.name));
            let variant_name = to_pascal_name(&variant.name);
            match &variant.fields {
                None => result.push_str(&format!("    {},\n", variant_name)),
                Some(fields) => {
                    result.push_str(&format!("    {} {{\n", variant_name));
                    for field in fields {
                        let ast::Field::Column(column) = field else {
                            continue;
                        };
                        let field_name = to_field_name(&column.name);
                        if field_name != column.name {
                            result.push_str(&format!(
                                "        #[serde(rename = {:?})]\n",
                                column.name
                            ));
                        }
                        let mut field_type = rust_type_for_column(&column.type_);
                        if column.nullable {
                            field_type = format!("Option<{}>", field_type);
                        }
                        result.push_str(&format!("        {}: {},\n", field_name, field_type));
                    }
                    result.push_str("    },\n");
                }
            }
        }
        result.push_str("}\n\n");
    }
    result
}

fn unique_name(name: &str, used: &mut HashSet<String>) -> String {
    let mut candidate = name.to_string();
    let mut suffix = 2;
    while !used.insert(candidate.clone()) {
        candidate = format!("{}{}", name, suffix);
        suffix += 1;
    }
    candidate
}

fn to_pascal_name(name: &str) -> String {
    let mut result = String::new();
    let mut capitalize_next = true;

    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() {
            if capitalize_next {
                result.push(ch.to_ascii_uppercase());
                capitalize_next = false;
            } else {
                result.push(ch);
            }
        } else {
            capitalize_next = true;
        }
    }

    if result.is_empty() {
        result.push_str("Generated");
    }
    if result.starts_with(|ch: char| ch.is_ascii_digit()) {
        result.insert(0, '_');
    }
    result
}

fn to_snake_name(name: &str) -> String {
    let mut result = String::new();
    let mut previous_was_separator = true;

    for (index, ch) in name.chars().enumerate() {
        if ch.is_ascii_alphanumeric() {
            if ch.is_ascii_uppercase() && index > 0 && !previous_was_separator {
                result.push('_');
            }
            result.push(ch.to_ascii_lowercase());
            previous_was_separator = false;
        } else if !previous_was_separator {
            result.push('_');
            previous_was_separator = true;
        }
    }

    let result = result.trim_matches('_').to_string();
    let result = if result.is_empty() {
        "generated".to_string()
    } else {
        result
    };
    raw_identifier(&result)
}

fn to_constant_name(name: &str) -> String {
    let snake = to_snake_name(name).trim_start_matches("r#").to_string();
    snake.to_ascii_uppercase()
}

fn to_field_name(name: &str) -> String {
    raw_identifier(&to_snake_name(&string::decapitalize(name)).trim_start_matches("r#"))
}

fn raw_identifier(name: &str) -> String {
    if rust_keywords().contains_key(name) {
        format!("r#{}", name)
    } else if name.starts_with(|ch: char| ch.is_ascii_digit()) {
        format!("_{}", name)
    } else {
        name.to_string()
    }
}

fn rust_keywords() -> HashMap<&'static str, ()> {
    [
        "as", "break", "const", "continue", "crate", "else", "enum", "extern", "false", "fn",
        "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref",
        "return", "self", "Self", "static", "struct", "super", "trait", "true", "type", "unsafe",
        "use", "where", "while", "async", "await", "dyn", "abstract", "become", "box", "do",
        "final", "macro", "override", "priv", "typeof", "unsized", "virtual", "yield", "try",
    ]
    .into_iter()
    .map(|keyword| (keyword, ()))
    .collect()
}
